import type { Metadata } from "next";
import { headers } from "next/headers";
import { fontScript, fontSans, fontMono } from "@/shared/config/fonts";
import { Header } from "@/widgets/header/Header";
import { Footer } from "@/widgets/footer/Footer";
import { Providers } from "./providers";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const nonce = (await headers()).get("x-nonce");

  return (
    <html
      lang="ru"
      className={`${fontScript.variable} ${fontSans.variable} ${fontMono.variable}`}
    >
      <body>
        <Providers>
          <Header />
          <main>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
